### ISSUE TITLE
Minor design fixes

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/Unstoppable-Wallet-Website#17]
- [ ] Adjust the minimum width to 360
- [ ] Fix the screenshots alignment (should be centered)
- [ ] Hide the "click here" button after clicking
- [ ] Fix the language alignment (right margin)
- [ ] Change background color of language menu to 2F323C

**Comment by uberkerim** [comment]
- [ ] Also need to move App Store/Play market/APK links from bottom to the top part of webpage.

**Comment by esengulov** [comment]
The issue is already implemented and no longer relevant
