### ISSUE TITLE
Press - webpage

### ISSUE THREAD

**Issue by uberkerim** [horizontalsystems/Unstoppable-Wallet-Website#20]
There should be another page "Press" where we can accumulate any external links about Unstoppable app. For example we can have article by Makeuseof about Unstoppable app, as well as listing of Unstoppable app in Choose Wallet section of Bitcoin.org

**Comment by esengulov** [comment]
> There should be another page "Press" where we can accumulate any external links about Unstoppable app. For example we can have article by Makeuseof about Unstoppable app, as well as listing of Unstoppable app in Choose Wallet section of Bitcoin.org

yep, new design has such section. I put it under the Partnerships. I think it sounds better than say 'In the news' or 'press'
