### ISSUE TITLE
Provide the adaptive layout for the mobile devices

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/Unstoppable-Wallet-Website#22]

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/rnuXo3g7KgRb5nMmRa9Uc0/Unstoppable-Web?node-id=3714%3A462

<img width="283" alt="Screen Shot 2020-01-24 at 3 07 39 PM" src="https://user-images.githubusercontent.com/42367908/73057275-47a4a380-3ebb-11ea-80b0-5180efa1576e.png">
