### ISSUE TITLE
Localize Unstoppable Wallet Website

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/Unstoppable-Wallet-Website#3]
- [ ] for each locale provide localized: 
-- text
-- images
-- app store / play market links.

**Comment by TalgatNurdinov** [comment]
- [ ] also Title text on header should be bolder 
- [ ] Remove duplicated title from RU, FR, TU, CH, KR languages 
- [ ] Add padding between device and cats

**Comment by esengulov** [comment]
This issues was dropped from the list due to lack of team consensus on the importance/need of the described feature
